services:
  - type: web
    name: umkm-backend
    env: docker
    region: oregon
    plan: free
    branch: master
    rootDir: be
    dockerfilePath: be/Dockerfile

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_KEY
        generateValue: true

      - key: APP_DEBUG
        value: false

      # Optional: Ganti ke PostgreSQL kalau Render DB kamu Postgre
      - key: DB_CONNECTION
        value: mysql

      - key: DB_HOST
        fromDatabase:
          name: umkm-db
          property: host

      - key: DB_PORT
        fromDatabase:
          name: umkm-db
          property: port

      - key: DB_DATABASE
        fromDatabase:
          name: umkm-db
          property: database

      - key: DB_USERNAME
        fromDatabase:
          name: umkm-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: umkm-db
          property: password
      # tambahin DB_HOST, DB_PORT, dsb kalau pakai database Render